#pragma once
#include "Animation.h"
#include <vector>

#define OBJECT_WIDTH 32
#define OBJECT_HEIGHT 32

#define MAX_WIDTH_SCREEN 1000
#define MAX_HEIGHT_SCREEN 700

#define SPEED 70
#define ATTACK_SPEED 50

//PLAYER
#define IDLE_PLAYER_FRAMES 6
#define IDLE_PLAYER_WIDTH 22
#define IDLE_PLAYER_HEIGHT 35

#define WALK_PLAYER_FRAMES 8
#define WALK_PLAYER_WIDTH 35
#define WALK_PLAYER_HEIGHT 30

#define HURT_PLAYER_FRAMES 4
#define HURT_PLAYER_WIDTH 25
#define HURT_PLAYER_HEIGHT 32

#define ATTACK_PLAYER_FRAMES 12
#define ATTACK_PLAYER_WIDTH 60
#define ATTACK_PLAYER_HEIGHT 45

#define DEAD_PLAYER_FRAMES 11
#define DEAD_PLAYER_WIDTH 45
#define DEAD_PLAYER_HEIGHT 45

#define SLIDE_PLAYER_FRAMES 5
#define SLIDE_PLAYER_WIDTH 40
#define SLIDE_PLAYER_HEIGHT 28


//ENEMY1
#define ATTACK_ENEMY1_FRAMES 8
#define ATTACK_ENEMY1_WIDTH 45
#define ATTACK_ENEMY1_HEIGHT 35

#define IDLE_ENEMY1_FRAMES 8
#define IDLE_ENEMY1_WIDTH 45
#define IDLE_ENEMY1_HEIGHT 38

#define HURT_ENEMY1_FRAMES 4
#define HURT_ENEMY1_WIDTH 45
#define HURT_ENEMY1_HEIGHT 45

#define DEATH_ENEMY1_FRAMES 4
#define DEATH_ENEMY1_WIDTH 60
#define DEATH_ENEMY1_HEIGHT 35

//ENEMY2

#define ATTACK_ENEMY2_FRAMES 8
#define ATTACK_ENEMY2_WIDTH 80
#define ATTACK_ENEMY2_HEIGHT 60

#define HURT_ENEMY2_FRAMES 4
#define HURT_ENEMY2_WIDTH 50
#define HURT_ENEMY2_HEIGHT 53

#define WALK_ENEMY2_FRAMES 4
#define WALK_ENEMY2_WIDTH 50
#define WALK_ENEMY2_HEIGHT 53

#define IDLE_ENEMY2_FRAMES 4
#define IDLE_ENEMY2_WIDTH 50
#define IDLE_ENEMY2_HEIGHT 53

#define DEATH_ENEMY2_FRAMES 4
#define DEATH_ENEMY2_WIDTH 60
#define DEATH_ENEMY2_HEIGHT 53




